### ISSUE TITLE
Create project BrowerRouter issues

### ISSUE THREAD

**Issue by gustavhartz** [Voxtir/voxtir#83]
The create project page triggers the following error in the frontend. Introduced in #75 

```
CreateProject.tsx:50 Warning: Cannot update a component (`BrowserRouter`) while rendering a different component (`CreateProject`). To locate the bad setState() call inside `CreateProject`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
    at CreateProject (http://localhost:5173/src/pages/CreateProject.tsx:18:26)
    at WithAccessToken (http://localhost:5173/src/components/Auth/with-access-token.tsx:16:45)
    at RenderedRoute (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=5699540b:3133:5)
    at Outlet (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=5699540b:3482:26)
    at WithAuthenticationRequired (http://localhost:5173/node_modules/.vite/deps/@auth0_auth0-react.js?v=5699540b:1507:14)
    at AuthenticationGuard (http://localhost:5173/src/components/Auth/authentication-guard.tsx:13:39)
    at div
    at div
    at div
    at Layout
    at RenderedRoute (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=5699540b:3133:5)
    at Routes (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=5699540b:3542:5)
    at div
    at App
    at Provider (http://localhost:5173/node_modules/.vite/deps/react-redux.js?v=5699540b:1198:3)
    at ApolloProvider (http://localhost:5173/node_modules/.vite/deps/@apollo_client.js?v=5699540b:129:19)
    at Auth0Provider (http://localhost:5173/node_modules/.vite/deps/@auth0_auth0-react.js?v=5699540b:1232:23)
    at Auth0ProviderWithNavigate (http://localhost:5173/src/components/Auth/auth0-provider-with-navigate.tsx:14:45)
    at Router (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=5699540b:3489:15)
    at BrowserRouter (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=5699540b:3938:5)
overrideMethod @ console.js:213
printWarning @ react-dom.development.js:86
error @ react-dom.development.js:60
warnAboutRenderPhaseUpdatesInDEV @ react-dom.development.js:27492
scheduleUpdateOnFiber @ react-dom.development.js:25498
dispatchSetState @ react-dom.development.js:17527
push @ history.ts:643
(anonymous) @ hooks.tsx:235
CreateProject @ CreateProject.tsx:50
renderWithHooks @ react-dom.development.js:16305
updateFunctionComponent @ react-dom.development.js:19588
beginWork @ react-dom.development.js:21601
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 19 more frames
Show less
```

**Comment by MadsFrost** [comment]
Fixed in #86
